name: PHPUnit

on:
  push:
    branches:
      - master

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
      - uses: php-actions/phpunit@v3
        with:
          php_version: 7.4
          php_extensions: ext-pcov
        env:
          STORAGENAME: ${{ secrets.STORAGENAME }}
          APIKEY: ${{ secrets.APIKEY }}