name: PHPUnit

on:
  push:
    branches:
      - v1
      - v2
      - v3
  schedule:
    - cron: '30 12,18 * * *'

jobs:
  test_v1:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php_version: [ 7.4, 8.0, 8.1 ]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: v1
      - uses: php-actions/composer@v5
        with:
          php_version: ${{ matrix.php_version }}
      - uses: php-actions/phpunit@v3
        with:
          php_version: ${{ matrix.php_version }}
        env:
          STORAGENAME: ${{ secrets.STORAGENAME }}
          APIKEY: ${{ secrets.APIKEY }}

  test_v2:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php_version: [ 7.4, 8.0, 8.1 ]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: v2
      - uses: php-actions/composer@v5
        with:
          php_version: ${{ matrix.php_version }}
      - uses: php-actions/phpunit@v3
        with:
          php_version: ${{ matrix.php_version }}
        env:
          STORAGENAME: ${{ secrets.STORAGENAME }}
          APIKEY: ${{ secrets.APIKEY }}

  test_v3:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php_version: [ 8.0, 8.1 ]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: v3
      - uses: php-actions/composer@v5
        with:
          php_version: ${{ matrix.php_version }}
      - uses: php-actions/phpunit@v3
        with:
          php_version: ${{ matrix.php_version }}
        env:
          STORAGENAME: ${{ secrets.STORAGENAME }}
          APIKEY: ${{ secrets.APIKEY }}