name: PHPUnit

on:
  push:
    branches:
      - master
      - v2
  schedule:
    - cron: '30 12,18 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
        with:
          php_version: 7.4
      - uses: php-actions/phpunit@v3
        with:
          php_version: 7.4
        env:
          STORAGENAME: ${{ secrets.STORAGENAME }}
          APIKEY: ${{ secrets.APIKEY }}